### ISSUE TITLE
NoClassDefFoundError: proguard.classfile.visitor.ClassVisitor when updating 2.2.0->2.3.0 on OpenJ9 JDK 8

### ISSUE THREAD

**Issue by Pr0methean** [wvengen/proguard-maven-plugin#112] opened 2020-08-11 20:46 UTC
My unit tests broke when https://github.com/Pr0methean/BetterRandom/commit/d022312755121c4824631a48f3652098f18eb965 was updated. On AdoptOpenJDK 8 with OpenJ9, on Linux x64, I get:
```
2020-08-10T08:11:13.5043938Z  [proguard] Error: A JNI error has occurred, please check your installation and try again
2020-08-10T08:11:13.5045328Z  [proguard] Exception in thread "main" java.lang.NoClassDefFoundError: proguard.classfile.visitor.ClassVisitor
2020-08-10T08:11:13.5046062Z  [proguard] 	at java.lang.J9VMInternals.prepareClassImpl(Native Method)
2020-08-10T08:11:13.5074949Z  [proguard] 	at java.lang.J9VMInternals.prepare(J9VMInternals.java:303)
2020-08-10T08:11:13.5077845Z  [proguard] 	at java.lang.Class.getMethodHelper(Class.java:1247)
2020-08-10T08:11:13.5078530Z  [proguard] 	at java.lang.Class.getMethod(Class.java:1191)
2020-08-10T08:11:13.5079201Z  [proguard] 	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
2020-08-10T08:11:13.5079912Z  [proguard] 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
2020-08-10T08:11:13.5081030Z  [proguard] Caused by: java.lang.ClassNotFoundException: proguard.classfile.visitor.ClassVisitor
2020-08-10T08:11:13.5081712Z  [proguard] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:591)
2020-08-10T08:11:13.5082349Z  [proguard] 	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
2020-08-10T08:11:13.5083017Z  [proguard] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
2020-08-10T08:11:13.5083640Z  [proguard] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
2020-08-10T08:11:13.5084293Z  [proguard] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
2020-08-10T08:11:13.5084832Z  [proguard] 	... 6 more
```
Doesn't affect JDK11 or JDK14 with OpenJ9, or JDK8, JDK11 or JDK14 with Hotspot.

**Comment by lasselindqvist** [comment] 2020-08-12 06:02
Can you check executing this directly from command line with the proguard-base JAR (https://mvnrepository.com/artifact/com.guardsquare/proguard-base/7.0.0)?
Check also if you have both of the Proguard JARs present in your build folder. If you do have them in the same folder, this most likely needs to be reported to Proguard or OpenJ9. If the proguard-core is missing, we can fix the problem here.

The class in question is this: https://github.com/Guardsquare/proguard-core/blob/master/src/proguard/classfile/visitor/ClassVisitor.java

**Comment by Pr0methean** [comment] 2020-08-12 23:15
The proguard-base jar isn't standalone:
```
$ /usr/lib/jvm/jdk8u265-b01/bin/java -jar ~/Downloads/proguard-base-7.0.0.jar target/BetterRandom-5.6.3-SNAPSHOT.jar 
no main manifest attribute, in /home/chris/Downloads/proguard-base-7.0.0.jar
```

**Comment by lasselindqvist** [comment] 2020-08-13 11:02
The actual command to run it is:
`java -cp proguard-base-7.0.0.jar proguard.ProGuard`

What I get when I run it only is
Error: Unable to initialize main class proguard.ProGuard
Caused by: java.lang.NoClassDefFoundError: proguard/classfile/attribute/visitor/AttributeVisitor

This happens because AttributeVisitor is in proguard-core and not proguard-base and proguard-code is not in classpath.

Running with
`java -cp "./*" proguard.ProGuard`
does work since it includes the core JAR also in the classpath.

So maybe it is something about how OpenJ9 handles classpaths.
The Java execution in this plugin is done with _org.apache.tools.ant.taskdefs.Java_ (Maven calling Ant basically)

To rule out this plugin as the problem, you need to check if both proguard-base and proguard-core are present when running with OpenJ9. If they are present the same way they are with OpenJDK. You can also add a log statement here -maven-plugin/blob/89773baa2255bd44748b84ac5224d5ebdaa93c8d/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L902 to see if both JARs are added to the class path. If they are found and added, Ant is most likely the place this needs to be fixed in.

**Comment by lasselindqvist** [comment] 2020-08-24 06:25
It is a problem. 7.0.0 should not be included.

https://github.com/wvengen/proguard-maven-plugin/blob/89773baa2255bd44748b84ac5224d5ebdaa93c8d/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L825

should add only the 6.1.1 and

https://github.com/wvengen/proguard-maven-plugin/blob/89773baa2255bd44748b84ac5224d5ebdaa93c8d/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L849

should then return that single artifact.

Would be helpful to see your full debug logs for the run (-X parameter in the Maven run) or if you can debug the getProguardJars method to see why it returns multiples.

**Comment by nicymike** [comment] 2020-08-24 07:22
The list pluginArtifacts has both dependency versions in it: Version 7 from plugin pom and version 6 from my own project.
https://github.com/wvengen/proguard-maven-plugin/blob/40c5b6abca4632094da7d8ea105a94de08e6015a/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L825

Version 6 will be added because I defined a version.
https://github.com/wvengen/proguard-maven-plugin/blob/40c5b6abca4632094da7d8ea105a94de08e6015a/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L832

But the loop goes on and because the other dependencies with version 7 also start with proguard, they will also be added.

7.0.0 is not equals to 6.1.1, so first if will be skipped
https://github.com/wvengen/proguard-maven-plugin/blob/40c5b6abca4632094da7d8ea105a94de08e6015a/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L832

Distance has not been recorded yet so it will go into second if and will add version 7.
https://github.com/wvengen/proguard-maven-plugin/blob/40c5b6abca4632094da7d8ea105a94de08e6015a/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L834

Core dependency of version 7 has the same distance now on my test so it will be added too.
https://github.com/wvengen/proguard-maven-plugin/blob/40c5b6abca4632094da7d8ea105a94de08e6015a/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L837

I think the main problem is the design of the loop because before adding version 7 there was a break inside the first if. But because we need two dependencies now, the break had to be removed.
If a version is defined, the loop should always check the version and skip proguard dependencies if version does not match. I think it would also be good to check if a dependency has already been added to proguardArtifacts and to not add a dependency twice (with different version maybe).

**Comment by lasselindqvist** [comment] 2020-08-24 07:39
(I was surprised that pluginArtifacts contains the default plugin dependencies and not just the ones the plugin user defines. It is explained a bit here: https://maven.apache.org/guides/mini/guide-maven-classloading.html#3-plugin-classloaders)

Yes adding the version check to all branches should fix the issue.

**Comment by nicymike** [comment] 2020-08-24 07:53
Good to known. Are you making the change to fix this?

**Comment by lasselindqvist** [comment] 2020-08-24 11:43
If someone makes the fixes, I can merge it, otherwise I will try to do it next weekend.

**Comment by nicymike** [comment] 2020-08-24 15:13
I'm on holiday this week and took the time to add a fix.

**Closed** 2020-08-24 19:04 UTC

**Comment by vamsi1027** [comment] 2022-12-31 17:06
Hi @lasselindqvist @nicymike @Pr0methean 

I have been facing issue with combination OpenJDK 11 ,Proguard base 6.1.1 version and Maven version 3.8.6.

Please can any take a look this.

 [proguard] ProGuard, version 6.1.1
 [proguard] Exception in thread "main" java.lang.NoSuchMethodError: proguard.io.ClassReader.<init>(ZZZLproguard/classfile/util/WarningPrinter;Lproguard/classfile/visitor/ClassVisitor;)V
 [proguard]     at proguard.InputReader.execute(InputReader.java:95)
 [proguard]     at proguard.ProGuard.readInput(ProGuard.java:266)
 [proguard]     at proguard.ProGuard.execute(ProGuard.java:97)
 [proguard]     at proguard.ProGuard.main(ProGuard.java:591)

**Comment by Pr0methean** [comment] 2023-01-03 18:16
@vamsi1027 Try updating Proguard base to a newer version. 6.1.1 is probably too old; I was using 7.0.0 when I encountered this bug, and that was two years ago.
