### ISSUE TITLE
not support windows 2012 x64 (but work on linux)

### ISSUE THREAD

**Issue by hynnet** [wvengen/proguard-maven-plugin#16] opened 2014-02-03 15:30 UTC
[DEBUG] proguardArtifact: C:\Users\myUser\.m2\repository\net\sf\proguar
d\proguard-base\4.11\proguard-base-4.11.jar
Project base dir set to: D:\Temp\maven\test\test-server
[INFO] proguard jar: C:\Users\myUser\.m2\repository\net\sf\proguard\pro
guard-base\4.11\proguard-base-4.11.jar
Execute:Java13CommandLauncher: Executing 'D:\jdk1.7.0_45\jre\bin\java.exe' with
arguments:
'-classpath'
'C:\Users\myUser\.m2\repository\net\sf\proguard\proguard-base\4.11\prog
uard-base-4.11.jar'
'proguard.ProGuard'
'-injars'
''D:\Temp\maven\test\test-server\target\test-server-1.0_proguard_base.jar'
(!META-INF/maven/**)'
'-libraryjars'
''C:\Users\myUser\.m2\repository\org\slf4j\slf4j-api\1.7.5\slf4j-api-1.
7.5.jar''
'-outjars'
''D:\Temp\maven\test\test-server\target\test-server-1.0.jar''
'-include'
''D:\Temp\maven\test\test-server\proguard.conf''
'-libraryjars'
''D:\jdk1.7.0_45\jre/lib/rt.jar''
'-libraryjars'
''D:\jdk1.7.0_45\jre/lib/jce.jar''
'-libraryjars'
''D:\jdk1.7.0_45\jre/lib/jsse.jar''
'-printmapping'
''D:\Temp\maven\test\test-server\target\proguard_map.txt''
'-printseeds'
''D:\Temp\maven\test\test-server\target\proguard_seeds.txt''
'-verbose'
'-keep public class * { public protected *; }'

The ' characters around the executable and arguments are
not part of the command.
 [proguard] Error: Expecting class path separator ';' before 's' in argument num
ber 4
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] test-server ..................................... FAILURE [11.555s]
[INFO] test ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.954s
[INFO] Finished at: Mon Feb 03 23:20:15 CST 2014
[INFO] Final Memory: 10M/179M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.wvengen:proguard-maven-plugin:2.0.7:pr
oguard (proguard) on project test-server: Obfuscation failed (result=1) -> [He
lp 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal c
om.github.wvengen:proguard-maven-plugin:2.0.7:proguard (proguard) on project test
-server: Obfuscation failed (result=1)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:216)

**Comment by FibreFoX** [comment] 2016-06-08 17:00
This might be able to get tested by AppVeyor, because they are free for OSS and provide "Windows Server 2012", as [stated on their website](http://www.appveyor.com/docs/installed-software#operating-system)

If this isn't worth the time, I vote for closing this issue as non-reproducable (no reproducable project available).

**Comment by wvengen** [comment] 2016-06-09 06:43
Let's close this. If anyone is interested in making this work better on Windows, please feel free to submit a PR.

**Closed by wvengen** 2016-06-09 06:43 UTC
