### ISSUE TITLE
multiple module maven project

### ISSUE THREAD

**Issue by ligaofeng0901** [wvengen/proguard-maven-plugin#70] opened 2018-04-17 09:56 UTC
module A depends on module B in a maven project, if I execute `mvn package` in parent project, then all moudles will be compiled one by one. First in module B, one class named `com.example.Test` will be changed to `com.a.A`, it's ok. Then in A, `com.example.Test` remains `com.example.Test` because B is **only** a dependency of A. I expect that the class `com.example.Test` will be changed to `com.a.A` when module B is compiling. how can I do it?

**Comment by FibreFoX** [comment] 2018-04-17 18:52
Can you provide a sample project with the scenario above? Maybe it's just a single configuration-issue and not a bug.

**Comment by ligaofeng0901** [comment] 2018-04-19 06:51
@FibreFoX hello, I have created a sample project.
## Detail of my project
file list:
```
.
└── project-parent
    ├── pom.xml
    ├── project-a
    │   ├── pom.xml
    │   └── src
    │       ├── main
    │       │   └── java
    │       │       └── com
    │       │           └── exampe
    │       │               └── Main.java
    │       └── test
    │           └── java
    └── project-b
        ├── pom.xml
        └── src
            └── main
                └── java
                    └── com
                        └── exampe
                            └── Test.java
```
the content of `pom.xml` in project-parent

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.exampe</groupId>
  <artifactId>project-parent</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>Archetype - project-parent</name>
  <url>http://maven.apache.org</url>
  <packaging>pom</packaging>
  <modules>
  	<module>project-a</module>
  	<module>project-b</module>
  </modules>
  
  <build>
  	<pluginManagement>
			<plugins>
				<plugin>
				    <groupId>com.github.wvengen</groupId>
				    <artifactId>proguard-maven-plugin</artifactId>
				    <version>2.0.14</version>
				    <executions>
				      <execution>
				         <phase>package</phase>
				         <goals>
				            <goal>proguard</goal>
				         </goals>
				      </execution>
				   </executions>
				</plugin>
			</plugins>
		</pluginManagement>
  </build>
</project>
```
the content of `pom.xml` in project-a
```xml
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <artifactId>project-a</artifactId>
  <name>project-a</name>
  <url>http://maven.apache.org</url>
  
  <parent>
    <groupId>com.exampe</groupId>
    <artifactId>project-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>
  
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  
  <build>
  	<plugins>
  		<plugin>
				<groupId>com.github.wvengen</groupId>
				<artifactId>proguard-maven-plugin</artifactId>
				<configuration>
					<attach>true</attach>
					<obfuscate>true</obfuscate>
					<attachArtifactClassifier>pg</attachArtifactClassifier>
					<options>
						<option>-target 1.8</option>
						<option>-dontoptimize</option>
						<option>-dontshrink</option>
						<option>-keepattributes Exceptions,InnerClasses,Signature,Deprecated,SourceFile,LocalVariable*Table,*Annotation*,Synthetic,EnclosingMethod</option>
						<option>-keep class a.b.c { *;}</option>
					</options>
					<outjar>${project.build.finalName}-pg.jar</outjar>
					<libs>
                                                 <lib>${java.home}/lib/rt.jar</lib>
                                          </libs>
                                          <outputDirectory>${project.build.directory}</outputDirectory>
				</configuration>
			</plugin>
  	</plugins>
  </build>
  <dependencies>
    <dependency>
    	<groupId>com.exampe</groupId>
    	<artifactId>project-b</artifactId>
    	<version>0.0.1-SNAPSHOT</version>
    </dependency>
  </dependencies>
</project>

```
the content of `pom.xml` in project-b
```xml
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  
  <artifactId>project-b</artifactId>
  <name>project-b</name>
  <url>http://maven.apache.org</url>
  
  <parent>
    <groupId>com.exampe</groupId>
    <artifactId>project-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>
  
  <build>
  	<plugins>
  		<plugin>
				<groupId>com.github.wvengen</groupId>
				<artifactId>proguard-maven-plugin</artifactId>
				<configuration>
					<attach>true</attach>
					<obfuscate>true</obfuscate>
					<attachArtifactClassifier>pg</attachArtifactClassifier>
					<options>
						<option>-target 1.8</option>
						<option>-dontoptimize</option>
						<option>-dontshrink</option>
						<option>-keepattributes Exceptions,InnerClasses,Signature,Deprecated,SourceFile,LocalVariable*Table,*Annotation*,Synthetic,EnclosingMethod</option>
						<option>-keep class a.b.c { *;}</option>
					</options>
					<injar>classes</injar>
					<outjar>${project.build.finalName}-pg.jar</outjar>
					<libs>
                                                 <lib>${java.home}/lib/rt.jar</lib>
                                        </libs>
                                        <outputDirectory>${project.build.directory}</outputDirectory>
				</configuration>
			</plugin>
  	</plugins>
  </build>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>

```
the content of `Test.java`
```java
package com.exampe;

public class Test {

    public void hello() {
        System.out.println("hello, I'm com.exampe.Test");
    }
}
```
the content of `Main.java`
```java
package com.exampe;

public class Main {

    private Test test;
    
    public void hello() {
        test = new Test();
        test.hello();
        System.out.println("I depend on com.example.Test in project-b");
    }
}
```
## Compile
then I execute `mvn package` in project-parent
file list
```
.
├── pom.xml
├── project-a
│   ├── pom.xml
│   ├── src
│   │   ├── main
│   │   │   └── java
│   │   │       └── com
│   │   │           └── exampe
│   │   │               └── Main.java
│   │   └── test
│   │       └── java
│   └── target
│       ├── classes
│       │   └── com
│       │       └── exampe
│       │           └── Main.class
│       ├── maven-archiver
│       │   └── pom.properties
│       ├── maven-status
│       │   └── maven-compiler-plugin
│       │       ├── compile
│       │       │   └── default-compile
│       │       │       ├── createdFiles.lst
│       │       │       └── inputFiles.lst
│       │       └── testCompile
│       │           └── default-testCompile
│       │               └── inputFiles.lst
│       ├── proguard_map.txt
│       ├── proguard_seed.txt
│       ├── project-a-0.0.1-SNAPSHOT-pg.jar
│       └── project-a-0.0.1-SNAPSHOT.jar
└── project-b
    ├── pom.xml
    ├── src
    │   └── main
    │       └── java
    │           └── com
    │               └── exampe
    │                   └── Test.java
    └── target
        ├── classes
        │   └── com
        │       └── exampe
        │           └── Test.class
        ├── classes-pg.jar
        ├── maven-archiver
        │   └── pom.properties
        ├── maven-status
        │   └── maven-compiler-plugin
        │       └── compile
        │           └── default-compile
        │               ├── createdFiles.lst
        │               └── inputFiles.lst
        ├── proguard_map.txt
        ├── proguard_seed.txt
        └── project-b-0.0.1-SNAPSHOT.jar
       └── project-b-0.0.1-SNAPSHOT-pg.jar
```
then I use `GD-GUI` to decompile the `project-a-0.0.1-SNAPSHOT-pg.jar` and `project-b-0.0.1-SNAPSHOT-pg.jar`.
the content of `Test.java` (in fact, it has been changed to `a.java`)is
```java
package a.a;

import java.io.PrintStream;

public class a
{
  public void a()
  {
    System.out.println("hello, I'm com.exampe.Test");
  }
}
```
 the content of `Main.java (in fact, it has been changed to `a.java`)` is
```java
package a.a;

import com.exampe.Test;
import java.io.PrintStream;

public class a
{
  private Test a;
  
  public void a()
  {
    this.a = new Test();
    this.a.hello();
    System.out.println("I depend on com.example.Test in project-b");
  }
}
```
## Run
finally, `project-a-0.0.1-SNAPSHOT-pg.jar` and `project-b-0.0.1-SNAPSHOT-pg.jar` will be put in the same path as libraries, but now, there are 2 class named `a`, and `com.exampe.Test` is not found.
I expect the result may be like this:
the content of `Test.java` (in fact, it has been changed to `a.java`)is
```java
package a.a;

import java.io.PrintStream;

public class a
{
  public void a()
  {
    System.out.println("hello, I'm com.exampe.Test");
  }
}
```
 the content of `Main.java` (in fact, it has been changed to `b.java`) is
```java
package a.a;

import java.io.PrintStream;

public class b
{
  private a a;
  
  public void a()
  {
    this.a = new a();
    this.a.hello();
    System.out.println("I depend on com.example.Test in project-b");
  }
}
```
How should I config my project, I have spent too much time to solve this problem, but no solution.

**Comment by JishengYuan** [comment] 2018-05-23 06:19
Hi, do you solve the problem? If there is a multiple module maven project, you should put the plugin configuration into project-a,  project-b and project-parent don't need configure the plugin.  Then add <assembly><inclusions>...</inclusions></assembly>, as follows:
In project-a:
       <plugin>
                <groupId>com.github.wvengen</groupId>
                <artifactId>proguard-maven-plugin</artifactId>
                <version>2.0.14</version>
                <configuration>
                    
                    <attach>false</attach> 
                    <obfuscate>true</obfuscate>
                    <attachArtifactClassifier>pg</attachArtifactClassifier>
                    <options>
                        <option>-target 1.8</option>
                        <option>-dontoptimize</option>
                        <option>-dontshrink</option>
                        <option>-keepattributes Exceptions,InnerClasses,Signature,Deprecated,SourceFile,LocalVariable*Table,*Annotation*,Synthetic,EnclosingMethod</option>
                    </options>
                    <injar>classes</injar>
                    <outjar>proguard-libs</outjar>
                    <libs>
                        <lib>${java.home}/lib/rt.jar</lib>
                    </libs>
                    <outputDirectory>${project.build.directory}</outputDirectory>
                    <assembly>
                        <inclusions>
                            <inclusion>
                                <groupId>com.example.hunxiao</groupId>
                                <artifactId>hunxiao-b</artifactId>
                            </inclusion>
                        </inclusions>
                    </assembly>
                </configuration>
         </plugin>

you need to tell the plugin that the dependencies of modules!

**Comment by lasselindqvist** [comment] 2019-07-17 18:10
Closing as not-a-bug.

**Closed by lasselindqvist** 2019-07-17 18:10 UTC
